name: CI

on:
  push:
    branches: [ v1.x.x ]
  pull_request:
    branches: [ v1.x.x ]

env:
  JAVA_VERSION: 12.x

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        flutter_channel: [ "stable", "beta" ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ matrix.flutter_channel }}

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        fail-on-warnings: true

    - name: Run unit tests
      run: flutter test --coverage

    - name: Upload unit tests coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info
        flags: unit,flutter-${{ matrix.flutter_channel }}

# vim: set et sw=2 sts=2 :
