name: CI

on:
  push:
    branches: [ v1.x.x ]
  pull_request:
    branches: [ v1.x.x ]

env:
  JAVA_VERSION: 12.x

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        flutter_channel: [ "stable", "beta" ]
        test_type: [ static, unit ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - uses: subosito/flutter-action@v1
      with:
        channel: ${{ matrix.flutter_channel }}

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze
      if: matrix.test_type == 'static'
      uses: zgosalvez/github-actions-analyze-flutter@v1
      with:
        fail-on-warnings: true

    - name: Run ${{ matrix.test_type }} tests
      if: matrix.test_type != 'static'
      run: tool/ci test-${{ matrix.test_type }}

    - name: Upload ${{ matrix.test_type }} tests coverage to Codecov
      if: matrix.test_type != 'static'
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        # We can't use coverage/*.lcov.info because is not supported. See:
        # https://github.com/codecov/codecov-bash/pull/400
        files: '*.lcov.info'
        flags: type-${{ matrix.test_type }},flutter-${{ matrix.flutter_channel }}

    - name: Save coverage reports as artifacts
      if: matrix.test_type != 'static'
      uses: actions/upload-artifact@v2
      with:
        name: coverage-${{ matrix.test_type }}-flutter_${{ matrix.flutter_channel }}
        path: coverage/*.lcov.info

# vim: set et sw=2 sts=2 :
